\c mosip_mvs 

GRANT CONNECT
   ON DATABASE mosip_mvs
   TO mvsuser;

GRANT USAGE
   ON SCHEMA mvs
   TO mvsuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA mvs
   TO mvsuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA mvs
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO mvsuser;

