-- America region countries
INSERT INTO mvs.country_region_mapping (country_name, region, cr_by, cr_dtimes) VALUES
('Argentina', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Bahamas', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Barbados', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Belize', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Bolivia', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Brazil', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Canada', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Chile', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Colombia', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Costa Rica', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Cuba', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Dominican Republic', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Ecuador', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('El Salvador', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Guatemala', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Guyana', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Honduras', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Jamaica', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Mexico', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Nicaragua', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Panama', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Paraguay', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Peru', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Suriname', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Trinidad and Tobago', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('United States', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Uruguay', 'America', 'SYSTEM', CURRENT_TIMESTAMP),
('Venezuela', 'America', 'SYSTEM', CURRENT_TIMESTAMP);

-- Australia region countries
INSERT INTO mvs.country_region_mapping (country_name, region, cr_by, cr_dtimes) VALUES
('Australia', 'Australia', 'SYSTEM', CURRENT_TIMESTAMP),
('Fiji', 'Australia', 'SYSTEM', CURRENT_TIMESTAMP),
('New Zealand', 'Australia', 'SYSTEM', CURRENT_TIMESTAMP),
('Papua New Guinea', 'Australia', 'SYSTEM', CURRENT_TIMESTAMP);

-- Asia region countries
INSERT INTO mvs.country_region_mapping (country_name, region, cr_by, cr_dtimes) VALUES
('Afghanistan', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Bangladesh', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Bhutan', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Brunei', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Cambodia', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('China', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Hong Kong', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('India', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Indonesia', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Japan', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Laos', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Malaysia', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Maldives', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Mongolia', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Myanmar', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Nepal', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('North Korea', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Pakistan', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Philippines', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Singapore', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('South Korea', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Sri Lanka', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Taiwan', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Thailand', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Timor-Leste', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP),
('Vietnam', 'Asia', 'SYSTEM', CURRENT_TIMESTAMP);

-- Europe & Middle East region countries
INSERT INTO mvs.country_region_mapping (country_name, region, cr_by, cr_dtimes) VALUES
('Albania', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Andorra', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Armenia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Austria', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Azerbaijan', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Bahrain', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Belarus', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Belgium', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Bosnia and Herzegovina', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Bulgaria', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Croatia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Cyprus', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Czech Republic', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Denmark', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Estonia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Finland', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('France', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Georgia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Germany', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Greece', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Hungary', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Iceland', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Iran', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Iraq', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Ireland', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Israel', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Italy', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Jordan', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Kosovo', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Kuwait', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Latvia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Lebanon', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Liechtenstein', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Lithuania', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Luxembourg', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Malta', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Moldova', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Monaco', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Montenegro', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Netherlands', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('North Macedonia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Norway', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Oman', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Palestine', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Poland', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Portugal', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Qatar', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Romania', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Russia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('San Marino', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Saudi Arabia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Serbia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Slovakia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Slovenia', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Spain', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Sweden', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Switzerland', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Syria', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Turkey', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Ukraine', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('United Arab Emirates', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('United Kingdom', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Vatican City', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP),
('Yemen', 'Europe & Middle East', 'SYSTEM', CURRENT_TIMESTAMP);

-- Africa region countries
INSERT INTO mvs.country_region_mapping (country_name, region, cr_by, cr_dtimes) VALUES
('Algeria', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Angola', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Benin', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Botswana', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Burkina Faso', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Burundi', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Cabo Verde', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Cameroon', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Central African Republic', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Chad', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Comoros', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Congo', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Djibouti', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Egypt', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Equatorial Guinea', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Eritrea', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Eswatini', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Ethiopia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Gabon', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Gambia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Ghana', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Guinea', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Guinea-Bissau', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Ivory Coast', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Kenya', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Lesotho', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Liberia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Libya', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Madagascar', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Malawi', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Mali', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Mauritania', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Mauritius', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Morocco', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Mozambique', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Namibia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Niger', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Nigeria', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Rwanda', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Sao Tome and Principe', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Senegal', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Seychelles', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Sierra Leone', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Somalia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('South Africa', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('South Sudan', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Sudan', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Tanzania', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Togo', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Tunisia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Zambia', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP),
('Zimbabwe', 'Africa', 'SYSTEM', CURRENT_TIMESTAMP);

-- Others region countries
INSERT INTO mvs.country_region_mapping (country_name, region, cr_by, cr_dtimes) VALUES
('American Samoa', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Anguilla', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Antarctica', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Antigua and Barbuda', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Aruba', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Bermuda', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Bonaire, Sint Eustatius and Saba', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Bouvet Island', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('British Indian Ocean Territory', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Cayman Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Christmas Island', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Cocos (Keeling) Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Cook Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Curacao', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Czechia', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Côte d''Ivoire', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Dominica', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Falkland Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Faroe Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('French Guiana', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('French Polynesia', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('French Southern Territories', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Gibraltar', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Greenland', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Grenada', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Guadeloupe', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Guam', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Guernsey', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Haiti', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Heard Island and McDonald Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Isle of Man', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Jersey', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Kiribati', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Macao', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Marshall Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Martinique', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Mayotte', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Micronesia', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Montserrat', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Nauru', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('New Caledonia', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Niue', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Norfolk Island', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Northern Mariana Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Palau', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Pitcairn', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Puerto Rico', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Reunion', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Barthelemy', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Helena', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Kitts and Nevis', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Lucia', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Martin', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Pierre and Miquelon', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Saint Vincent and the Grenadines', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Samoa', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Sint Maarten', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Solomon Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('South Georgia and the South Sandwich Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Svalbard and Jan Mayen', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Tokelau', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Tonga', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Turks and Caicos Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Tuvalu', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('United States Minor Outlying Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Vanuatu', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Virgin Islands, British', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Virgin Islands, U.S.', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Wallis and Futuna', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Western Sahara', 'Others', 'SYSTEM', CURRENT_TIMESTAMP),
('Aland Islands', 'Others', 'SYSTEM', CURRENT_TIMESTAMP);